#
services:
  ollama:
    image: dockerapp/ollama
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - HOSTOS=darwin
        - HOSTARCH=arm64
        # - HOSTOS=linux
        # - HOSTARCH=amd64